/** Curated emoji library with search keywords for the admin picker. */
export const EMOJI_CATEGORIES = [
  {
    id: "celebrations",
    label: "Celebrations",
    emojis: [
      { emoji: "🎉", keywords: ["party", "celebration", "confetti"] },
      { emoji: "🎊", keywords: ["confetti", "ball", "party"] },
      { emoji: "🎈", keywords: ["balloon", "party", "birthday"] },
      { emoji: "🎂", keywords: ["birthday", "cake", "celebration"] },
      { emoji: "🧁", keywords: ["cupcake", "dessert", "sweet"] },
      { emoji: "🍰", keywords: ["cake", "slice", "dessert"] },
      { emoji: "🥳", keywords: ["party", "celebrate", "face"] },
      { emoji: "🎁", keywords: ["gift", "present", "box"] },
      { emoji: "🎀", keywords: ["ribbon", "bow", "gift"] },
      { emoji: "✨", keywords: ["sparkle", "star", "magic"] },
      { emoji: "🎆", keywords: ["fireworks", "night", "celebration"] },
      { emoji: "🎇", keywords: ["sparkler", "fireworks"] },
      { emoji: "🪅", keywords: ["pinata", "party"] },
      { emoji: "🎪", keywords: ["circus", "tent", "event"] },
      { emoji: "🎭", keywords: ["theater", "drama", "masks"] },
      { emoji: "🎵", keywords: ["music", "note", "song"] },
      { emoji: "🎶", keywords: ["music", "notes", "melody"] },
      { emoji: "🎤", keywords: ["microphone", "karaoke", "sing"] },
      { emoji: "🎧", keywords: ["headphones", "music"] },
      { emoji: "🎸", keywords: ["guitar", "music", "rock"] },
      { emoji: "🥂", keywords: ["champagne", "toast", "cheers"] },
      { emoji: "🍾", keywords: ["champagne", "bottle", "celebration"] },
      { emoji: "🍻", keywords: ["beer", "cheers", "drinks"] },
      { emoji: "🪩", keywords: ["disco", "ball", "dance"] },
    ],
  },
  {
    id: "wedding",
    label: "Wedding & Love",
    emojis: [
      { emoji: "💒", keywords: ["wedding", "church", "marriage"] },
      { emoji: "💍", keywords: ["ring", "engagement", "proposal"] },
      { emoji: "👰", keywords: ["bride", "wedding", "veil"] },
      { emoji: "🤵", keywords: ["groom", "suit", "wedding"] },
      { emoji: "💐", keywords: ["bouquet", "flowers", "wedding"] },
      { emoji: "🌹", keywords: ["rose", "flower", "love"] },
      { emoji: "❤️", keywords: ["heart", "love", "red"] },
      { emoji: "💕", keywords: ["hearts", "love", "pink"] },
      { emoji: "💖", keywords: ["heart", "sparkle", "love"] },
      { emoji: "💗", keywords: ["heart", "growing", "love"] },
      { emoji: "💓", keywords: ["heartbeat", "love"] },
      { emoji: "💞", keywords: ["hearts", "revolving", "love"] },
      { emoji: "💑", keywords: ["couple", "love"] },
      { emoji: "👫", keywords: ["couple", "people"] },
      { emoji: "🕊️", keywords: ["dove", "peace", "wedding"] },
      { emoji: "🪷", keywords: ["lotus", "flower", "mayoun"] },
      { emoji: "🧿", keywords: ["nazar", "evil eye", "protection"] },
      { emoji: "🏛️", keywords: ["classical", "building", "venue"] },
      { emoji: "⛪", keywords: ["church", "venue"] },
      { emoji: "🕌", keywords: ["mosque", "venue"] },
    ],
  },
  {
    id: "flowers",
    label: "Flowers & Nature",
    emojis: [
      { emoji: "🌸", keywords: ["cherry", "blossom", "flower", "pink"] },
      { emoji: "🌺", keywords: ["hibiscus", "flower", "tropical"] },
      { emoji: "🌼", keywords: ["daisy", "flower", "holud"] },
      { emoji: "🌻", keywords: ["sunflower", "flower", "yellow"] },
      { emoji: "🌷", keywords: ["tulip", "flower", "spring"] },
      { emoji: "💮", keywords: ["flower", "white", "floral"] },
      { emoji: "🏵️", keywords: ["rosette", "award", "flower"] },
      { emoji: "🌿", keywords: ["herb", "leaf", "green", "greenery"] },
      { emoji: "🍃", keywords: ["leaves", "wind", "green"] },
      { emoji: "🌱", keywords: ["seedling", "plant", "grow"] },
      { emoji: "🪴", keywords: ["potted", "plant", "decor"] },
      { emoji: "🌴", keywords: ["palm", "tree", "tropical"] },
      { emoji: "🌵", keywords: ["cactus", "desert", "plant"] },
      { emoji: "🍂", keywords: ["fall", "leaves", "autumn"] },
      { emoji: "🍁", keywords: ["maple", "leaf", "fall"] },
      { emoji: "🌈", keywords: ["rainbow", "color", "pride"] },
      { emoji: "☀️", keywords: ["sun", "sunny", "bright"] },
      { emoji: "🌙", keywords: ["moon", "night", "crescent"] },
      { emoji: "⭐", keywords: ["star", "gold", "sparkle"] },
      { emoji: "🌟", keywords: ["star", "glowing", "shine"] },
    ],
  },
  {
    id: "baby",
    label: "Baby & Family",
    emojis: [
      { emoji: "🍼", keywords: ["baby", "bottle", "shower"] },
      { emoji: "👶", keywords: ["baby", "face", "child"] },
      { emoji: "🧸", keywords: ["teddy", "bear", "toy", "baby"] },
      { emoji: "🎀", keywords: ["ribbon", "bow", "pink"] },
      { emoji: "🧷", keywords: ["safety", "pin", "diaper"] },
      { emoji: "🛁", keywords: ["bath", "tub", "baby"] },
      { emoji: "🧴", keywords: ["lotion", "bottle", "baby"] },
      { emoji: "🧦", keywords: ["socks", "baby", "clothing"] },
      { emoji: "👪", keywords: ["family", "parents", "child"] },
      { emoji: "👨‍👩‍👧", keywords: ["family", "girl"] },
      { emoji: "👨‍👩‍👦", keywords: ["family", "boy"] },
      { emoji: "🎠", keywords: ["carousel", "horse", "fair"] },
      { emoji: "🎡", keywords: ["ferris", "wheel", "fair"] },
      { emoji: "🛝", keywords: ["slide", "playground"] },
      { emoji: "🧩", keywords: ["puzzle", "piece", "toy"] },
      { emoji: "🪆", keywords: ["nesting", "dolls", "matryoshka"] },
    ],
  },
  {
    id: "decor",
    label: "Decor & Props",
    emojis: [
      { emoji: "💡", keywords: ["light", "bulb", "neon", "idea"] },
      { emoji: "🕯️", keywords: ["candle", "light", "romantic"] },
      { emoji: "🏮", keywords: ["lantern", "red", "paper"] },
      { emoji: "🪔", keywords: ["diya", "lamp", "oil"] },
      { emoji: "✨", keywords: ["sparkle", "glitter", "shine"] },
      { emoji: "🪞", keywords: ["mirror", "decor"] },
      { emoji: "🖼️", keywords: ["frame", "picture", "art"] },
      { emoji: "🪑", keywords: ["chair", "seating", "furniture"] },
      { emoji: "🛋️", keywords: ["couch", "sofa", "lounge"] },
      { emoji: "🪵", keywords: ["wood", "log", "rustic"] },
      { emoji: "🧺", keywords: ["basket", "linen", "picnic"] },
      { emoji: "🎈", keywords: ["balloon", "decor"] },
      { emoji: "🎐", keywords: ["wind", "chime", "decor"] },
      { emoji: "🪄", keywords: ["magic", "wand", "sparkle"] },
      { emoji: "👑", keywords: ["crown", "royal", "queen", "king"] },
      { emoji: "💎", keywords: ["gem", "diamond", "luxury"] },
      { emoji: "🔮", keywords: ["crystal", "ball", "mystic"] },
      { emoji: "🎀", keywords: ["ribbon", "bow", "decor"] },
      { emoji: "📦", keywords: ["box", "package", "blocks"] },
      { emoji: "🧱", keywords: ["brick", "blocks", "build"] },
      { emoji: "🏛️", keywords: ["pillar", "column", "stand"] },
      { emoji: "🎬", keywords: ["clapper", "film", "photo"] },
      { emoji: "📷", keywords: ["camera", "photo", "booth"] },
      { emoji: "🎥", keywords: ["video", "camera", "film"] },
      { emoji: "🔊", keywords: ["speaker", "audio", "sound"] },
      { emoji: "📢", keywords: ["megaphone", "announce"] },
      { emoji: "🎓", keywords: ["graduation", "cap", "school"] },
    ],
  },
  {
    id: "food",
    label: "Food & Drinks",
    emojis: [
      { emoji: "🍽️", keywords: ["plate", "dining", "tableware"] },
      { emoji: "🍴", keywords: ["fork", "knife", "cutlery"] },
      { emoji: "🥄", keywords: ["spoon", "cutlery"] },
      { emoji: "🍲", keywords: ["pot", "food", "stew", "buffet"] },
      { emoji: "🍱", keywords: ["bento", "box", "tray"] },
      { emoji: "🧁", keywords: ["cupcake", "dessert"] },
      { emoji: "🍩", keywords: ["donut", "dessert", "sweet"] },
      { emoji: "🍪", keywords: ["cookie", "dessert"] },
      { emoji: "🍫", keywords: ["chocolate", "bar", "sweet"] },
      { emoji: "🍬", keywords: ["candy", "sweet"] },
      { emoji: "🍭", keywords: ["lollipop", "candy"] },
      { emoji: "🍷", keywords: ["wine", "glass", "drink"] },
      { emoji: "🍸", keywords: ["cocktail", "drink", "martini"] },
      { emoji: "🍹", keywords: ["tropical", "drink", "mocktail"] },
      { emoji: "☕", keywords: ["coffee", "tea", "hot"] },
      { emoji: "🧃", keywords: ["juice", "box", "drink"] },
      { emoji: "🍕", keywords: ["pizza", "food", "party"] },
      { emoji: "🍔", keywords: ["burger", "food"] },
      { emoji: "🌮", keywords: ["taco", "food", "mexican"] },
      { emoji: "🍣", keywords: ["sushi", "japanese", "food"] },
    ],
  },
  {
    id: "symbols",
    label: "Symbols & More",
    emojis: [
      { emoji: "⚙️", keywords: ["gear", "settings", "global"] },
      { emoji: "🔧", keywords: ["wrench", "tools", "setup"] },
      { emoji: "📌", keywords: ["pin", "mark", "important"] },
      { emoji: "📍", keywords: ["location", "pin", "map"] },
      { emoji: "🏷️", keywords: ["label", "tag", "price"] },
      { emoji: "🔖", keywords: ["bookmark", "tag"] },
      { emoji: "✅", keywords: ["check", "done", "yes"] },
      { emoji: "💯", keywords: ["hundred", "perfect", "score"] },
      { emoji: "🔥", keywords: ["fire", "hot", "trending"] },
      { emoji: "💫", keywords: ["dizzy", "star", "magic"] },
      { emoji: "🌟", keywords: ["star", "featured"] },
      { emoji: "🏆", keywords: ["trophy", "award", "winner"] },
      { emoji: "🥇", keywords: ["medal", "gold", "first"] },
      { emoji: "🎯", keywords: ["target", "goal", "dart"] },
      { emoji: "🏢", keywords: ["office", "corporate", "building"] },
      { emoji: "🏠", keywords: ["house", "home", "venue"] },
      { emoji: "🏡", keywords: ["house", "garden", "home"] },
      { emoji: "🌍", keywords: ["earth", "globe", "world"] },
      { emoji: "🎌", keywords: ["flags", "crossed", "japan"] },
      { emoji: "🇨🇦", keywords: ["canada", "flag"] },
      { emoji: "🇧🇩", keywords: ["bangladesh", "flag"] },
      { emoji: "🕌", keywords: ["mosque", "islamic"] },
      { emoji: "🕉️", keywords: ["om", "hindu"] },
      { emoji: "☸️", keywords: ["dharma", "wheel"] },
    ],
  },
];

export const ALL_EMOJIS = EMOJI_CATEGORIES.flatMap((cat) => cat.emojis);

export const DEFAULT_EMOJI = "🎉";

export function searchEmojis(query) {
  const q = query.trim().toLowerCase();
  if (!q) return ALL_EMOJIS;
  return ALL_EMOJIS.filter(
    (entry) => entry.emoji.includes(q) || entry.keywords.some((kw) => kw.includes(q))
  );
}

export function getUniqueEmojis(entries) {
  const seen = new Set();
  return entries.filter((entry) => {
    if (seen.has(entry.emoji)) return false;
    seen.add(entry.emoji);
    return true;
  });
}
